# added for CDP compliance: https://tmobile.gitlab.io/cdp/community-hub/documentation/COMMON/#usage
include:
  - project: 'tmobile/templates'
    ref: tmo/master
    file: '/gitlab-ci/.tmo.global.common.gitlab-ci.yml'

# exclude running pipeline on pushes for all jobs
# workflow:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "push"'
#       when: never

stages:
  - tmo
  - test
  - load-pipeline-module
  - test-cases-for-modules

variables:
  JAZZ_IMAGE_PREFIX: "registry.gitlab.com/tmobile/jazz/core/packages/base"
  JAZZ_IMAGE_TAG: "1.0.0"
  SCRIPTS_REPO: https://$GITLAB_SVC_ACCT_USER:$GITLAB_SVC_ACCT_PASSWORD@gitlab.com/tmobile/jazz/core/jazz-pipeline-module.git
  WORKING_DIRECTORY: WorkingDirectory
  WORKING_MODULE_DIRECTORY: $WORKING_DIRECTORY/jazz-pipeline-module
  
# load modules from remote location
job 'Load Modules':
  stage: load-pipeline-module
  image: "$JAZZ_IMAGE_PREFIX/master:$JAZZ_IMAGE_TAG"
  script:
    - git clone -b master $SCRIPTS_REPO $WORKING_MODULE_DIRECTORY
  except:
    - pushes    
  artifacts:
    paths:
      - $WORKING_DIRECTORY
  
# test cases for modules
job 'Unit Tests':
  stage: test-cases-for-modules
  image: "$JAZZ_IMAGE_PREFIX/master:$JAZZ_IMAGE_TAG"
  script:
    - test/ModuleTest.sh
  except:
    - pushes    
  artifacts:
    paths:
      - $WORKING_DIRECTORY
