baseURL = "https://docs.jazz.corporate.t-mobile.com"
languageCode = "en-us"
title = "Jazz Documentation"
theme = "tmo-cloud-docs"
homeLink = "https://jazz.corporate.t-mobile.com"
staticDir = "static"


[outputs]
    home = ["HTML", "RSS"]

[params]
    nav_links = [
        { text="Features", link="https://jazz.corporate.t-mobile.com/#features" },
        { text="About", link="https://jazz.corporate.t-mobile.com/#About" },
        { text="Github", link="https://github.com/tmobile/jazz" },
        { text="API", link="/api" },
        { text="Using Jazz", link="/" }
    ]
    header_text = "DOCUMENTATION"
    homeLink = "https://jazz.corporate.t-mobile.com"
    footer_links = [
        { text="Copyright 2019", click="no" },
        { text="All rights reserved", click="no" },
        { text="Privacy Policy", link="https://www.t-mobile.com/company/website/privacypolicy.aspx", click="yes" }
    ]
    redocPackage = "https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js"
    swaggerHost = "https://s3-us-west-2.amazonaws.com/cloud-api-doc.corporate.t-mobile.com"

