
stages:
  - tmo
  - test
  - jazz-deployment

jazz-deployment-pipeline:
  stage: jazz-deployment 
  variables:
    REPO_URL: ${CI_PROJECT_URL}.git
    REPO_BRANCH: $CI_COMMIT_REF_NAME
    COMMIT_SHA: $CI_COMMIT_SHA
    REPO_NAME: $CI_PROJECT_NAME
    USER_CI_PIPELINE_ID: $CI_PIPELINE_ID
    USER_CI_PIPELINE_URL: $CI_PIPELINE_URL
  trigger:
    project: /jazz/core/website-pipeline
    strategy: depend    
    
