# added for CDP compliance: https://tmobile.gitlab.io/cdp/community-hub/documentation/COMMON/#usage
include:
  - project: 'tmobile/templates'
    file: '/gitlab-ci/.tmo.global.common.gitlab-ci.yml'

# exclude running pipeline on pushes for all jobs
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - when: always

stages:
  - tmo
  - test
  - rollback

# Ref: https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories
# - echo -e "machine gitlab.com\nlogin git\npassword ${GITLAB_SVC_ACCT_PASSWORD}" > ~/.netrc
.netrc: &setnetrc
  - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc

variables:
  API_BASE_URL: https://cloud-api.corporate.t-mobile.com/api/jazz
  SCRIPTS_REPO: https://$GITLAB_SVC_ACCT_USER:$GITLAB_SVC_ACCT_PASSWORD@gitlab.com/tmobile/jazz/core/jazz-pipeline-module.git
  SERVERLESS_CONFIG_REPO:  https://$GITLAB_SVC_ACCT_USER:$GITLAB_SVC_ACCT_PASSWORD@gitlab.com/tmobile/jazz/core/serverless-config-pack.git
  INITIALIZE_IMAGE: registry.gitlab.com/tmobile/jazz/core/packages/groovy-npm-lite:1.0.0
  ROLLBACK_IMAGE: registry.gitlab.com/tmobile/jazz/core/packages/groovy-serverless:1.0.0
  WORKING_DIRECTORY: WorkingDirectory
  WORKING_MODULE_DIRECTORY: $WORKING_DIRECTORY/jazz-pipeline-module
  EVENT_HANDLER: GITLAB_CI
  EVENT_TYPE: SERVICE_DEPLOYMENT
  AWS_DEFAULT_REGION: us-west-2

#@Pipeline trigger params {REPO_URL, REPO_BRANCH, COMMIT_SHA), REPO_NAME, REQUEST_ID - Optional

rollback:
  stage: rollback
  image: $ROLLBACK_IMAGE  
  script:
    - *setnetrc
    - bash scripts/LoadConfigs.sh
    - groovy -cp $WORKING_MODULE_DIRECTORY/ scripts/RollbackPipelineUtility.groovy configRollback || exit 1
  artifacts:
    when: always
    paths:
      - $WORKING_DIRECTORY


